[package]
name = "koikatsu-hamster"
version = "0.1.0"
description = "Sorts Koikatsu card PNGs into per-game folders"
authors = ["soapproject"]
license = "MIT"
repository = "https://github.com/soapproject/koikatsu-hamster-rs"
edition = "2021"
rust-version = "1.70"

[dependencies]

[profile.release]
strip = true
